config/routes.rb
Mystore::Application.routes.draw do

  Spree::Core::Engine.routes.prepend do
    resources :activities, :controller => "products"
    root :to => 'home#home_page'
    ["Home", "Activities", "Contact", "About Us", "Faqs", "Partners And Operators", "Privacy Policy", "Terms And Conditions"].each do |item|
      match '/pages/:page_name' => 'home#show_pages'
    end
    namespace :admin do
      resources :activities, :controller => "products"
    end
  end

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.append do
    devise_for :users,
               :class_name => Spree::User,
               :skip => [:unlocks],
               :controllers => { :sessions => 'spree/user_sessions', 
               :omniauth_callbacks => "spree/omniauth_callbacks",
               :registrations => 'spree/user_registrations' }
    resources  :user_authentications
    match 'account' => 'users#show', :as => 'user_root'
    namespace :admin do
      resources :authentication_methods
    end
  end

  

end

app/controllers/products_controller.rb
 Spree::ProductsController.class_eval do
   def index
     # q = make_query_params(params)
     # @searcher = Spree::Config.searcher_class.new(params[:activity_type])
     # @products = @searcher.retrieve_products
     # After much trial and error, I have decided to let go of spree's default search and implement my own based on sunspot.
     @current = 'products'
     @search = Sunspot.search(Spree::Variant) do
       with :is_active, true
       @products = @search.results
     end
   end
  

   private
   def make_query_params(params)
     q = ""
     Spree::Product::SEARCH_FIELDS.each do |field|
       if params[field]
         q += params[field]
       end
     end
     return q
   end
 end

app/views/spree/admin/products/_fixed_size_form.html.haml
%div{"data-hook" => "admin_product_form_fields"}
  %p.small
    %strong Note &nbsp;
    You do not need to create a separate variant for fixed group size activities. You can enter the pricing information here itself.
  .clearfix
    .left{"data-hook" => "admin_product_form_left"}
      = f.inputs :name=>"Basic Details" do
        = f.input :name,           :required=> true,    :hint=>"This is the title of the activity. Appears in h1"
        = f.input :street_address, :required=> true
        = f.input :city,           :required=> true
        = f.input :state,          :required=> true,:as => :select, :collection=> Spree::Product::LIST_OF_STATES, :required=>true
        = f.input :level,               :as => :select, :collection=> Spree::Product::LEVELS, :required=>true, :hint=>"Level of the activity"
        = f.input :duration,            :hint=> "the duration of activity. in minutes, to maintain uniformity."
        = f.input :description,         :hint=> "This is a brief 2-3 line description", :as=>"text"
        = f.input :min_passengers_reqd, :required=>true
        = f.input :max_passengers_reqd, :required=>true
      = f.inputs :name => "When does this go live on the site?" do
        = f.input :available_on, :as => :datetime, :hint => "(#{time_ago_in_words @product.available_on if @product.available_on})"

      = f.inputs :name => "for generating map" do
        %h6
          you can use 
          %a{:href=>"http://www.findlatitudeandlongitude.com/", :target=>"blank"}a service like this one
          to find on the lat and long positions
        .small
          default coordinates are set to bangalore
        = f.input :latitude, :input_html => {:value => "#{@product.new_record? ? 12.9716060 : @product.latitude}"}
        = f.input :longitude, :input_html => {:value => "#{@product.new_record? ? 77.5943760 : @product.longitude}"}
        = f.input :zoom_level, :input_html => {:value => "#{@product.new_record? ? 3 : @product.zoom_level}"}
      = f.inputs :name => "for SEO purposes" do
        = f.input :permalink, :hint => "please change it only once"
        = f.input :meta_description
        = f.input :meta_keywords
      - if Spree::Config[:track_inventory_levels]
        = f.inputs :name => "Day Wise Stock", :class => "price_matrix" do
          -# = f.input :on_hand, :label=> "Default stock on hand (per day)", :input_html => {"data-hook" => "price"}, :hint => "If you provide this, all daily stock amounts will be overridden. To black out a particular day of the weel, enter zero or leave that field blank. The blank ones will not be defaulted to the default value."
          -# %br
          - Date::DAYNAMES.each do |day|
            = f.input "on_hand_on_#{day.downcase}".to_sym
      = f.inputs :name => "Day Wise Pricing", :class => "price_matrix" do
        = f.input :price, :label=> "Default Price", :input_html => {"data-hook" => "price"}      ,:hint => "This will be the fall back price in case a price is not defined below. For quicker data entry, enter the default price and then just set changed prices for whichever day of the week it actually changes."
        %br
        - Date::DAYNAMES.each do |day|
          = f.input "price_on_#{day.downcase}".to_sym


    .right{"data-hook" => "admin_product_form_right"}      
      = f.inputs :name=>"HTML fields" do
        - ["Overview", "Highlights", "Features", "Exclusions", "Cancellation Policy"].each do |field|
          = f.input field.underscore.gsub(' ', '_' ).to_sym, :as=>"text", :input_html=>{:class=>"wysiwyg"}
      





      -# = f.field_container :available_on do
      -#   = f.label :available_on, t(:available_on)
      -#   %br/
      -#   = f.error_message_on :available_on
      -#   = f.text_field :available_on, :class => 'datepicker'


      - unless @product.has_variants?
        = f.field_container :sku do
          = f.label :sku, t(:sku)
          %br/
          = f.text_field :sku, :size => 16



        -# - if Spree::Config[:track_inventory_levels]
        -#   = f.field_container :on_hand do
        -#     = f.label :on_hand, t(:on_hand)
        -#     %br/
        -#     = f.number_field :on_hand, :min => 0
      -#   %ul#shipping_specs
      -#     %li#shipping_specs_weight_field
      -#       = f.label :weight, t(:weight)
      -#       = f.text_field :weight, :size => 4
      -#     %li#shipping_specs_height_field
      -#       = f.label :height, t(:height)
      -#       = f.text_field :height, :size => 4
      -#     %li#shipping_specs_width_field
      -#       = f.label :width, t(:width)
      -#       = f.text_field :width, :size => 4
      -#     %li#shipping_specs_depth_field
      -#       = f.label :depth, t(:depth)
      -#       = f.text_field :depth, :size => 4
      -# = f.field_container :shipping_categories do
      -#   = f.label :shipping_category_id, t(:shipping_categories)
      -#   %br/
      -#   = f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, { :include_blank => true }, { 'style' => 'width:200px' })
      -#   = f.error_message_on :shipping_category
      -# = f.field_container :tax_category do
      -#   = f.label :tax_category_id, t(:tax_category)
      -#   %br/
      -#   = f.collection_select(:tax_category_id, @tax_categories, :id, :name, { :include_blank => true }, { 'style' => 'width:200px' })
      -#   = f.error_message_on :tax_category
  -# %div{"data-hook" => "admin_product_form_additional_fields"}
  -#   - Spree::Variant.additional_fields.select { |af| af[:only].nil? || af[:only].include?(:product) }.each do |field|
  -#     = render :partial => 'spree/admin/shared/additional_field', :locals => { :field => field, :f => f }

app/views/spree/admin/products/_form.html.haml
%div{"data-hook" => "admin_product_form_fields"}
  .clearfix
    .left{"data-hook" => "admin_product_form_left"}
      = f.inputs :name=>"Basic Details" do
        = f.input :name,            :required=> true,    :hint=>"This is the title of the activity. Appears in h1"
        = f.input :taxons,          :required=> true,:as => :select, :collection=> Spree::Taxon.all_activity_types, :hint => "Logically an activity can belong to multiple taxons. But please select one.", :input_html => { :style => "height: 10em" }
        %br
        = f.input :featured, :hint=>"Featured activities will be shown on the home page"
        = f.input :street_address, :required=> true
        = f.input :city,           :required=> true
        = f.input :state,          :required=> true,:as => :select, :collection=> Spree::Product::LIST_OF_STATES, :required=>true
        = f.input :level,               :as => :select, :collection=> Spree::Product::LEVELS, :required=>true, :hint=>"Level of the activity", :selected => "#{@product.level.blank? ? '' : @product.level}"
        = f.input :duration,            :hint=> "the duration of activity. in minutes, to maintain uniformity.", :input_html => {:value => 30}
        = f.input :description,         :hint=> "This is a brief 2-3 line description", :as=>"text"
     
        -# = f.input :min_passengers_reqd, :required=>true,                                :class=>"fl", :input_html => {:value => 1}
        -# = f.input :max_passengers_reqd, :required=>true,                                :input_html => {:value => 1}
      = f.inputs :name => "for generating map" do
        %h6
          you can use 
          %a{:href=>"http://www.findlatitudeandlongitude.com/", :target=>"blank"}a service like this one
          to find on the lat and long positions
        .small
          default coordinates are set to bangalore
        = f.input :latitude, :input_html => {:value => "#{@product.new_record? ? 12.9716060 : @product.latitude}"}
        = f.input :longitude, :input_html => {:value => "#{@product.new_record? ? 77.5943760 : @product.longitude}"}
        = f.input :zoom_level, :input_html => {:value => "#{@product.new_record? ? 3 : @product.zoom_level}"}
      = f.inputs :name=>"HTML fields" do
        - ["Overview", "Highlights", "Features", "Reviews", "itinerary", "Cancellation Policy"].each do |field|
          = f.input field.underscore.gsub(' ', '_' ).to_sym, :as=>"text", :input_html=>{:class=>"wysiwyg"}
    .right{"data-hook" => "admin_product_form_right"}      
      = f.inputs :name => "When does this go live on the site?" do
        = f.input :available_on
      = f.inputs :name => "What is the bookable period?", :class => "price_matrix"  do
        = f.input :bookable_from, :hint => "Start of booking range", :as => :string, :input_html => { :type => "date" }
        = f.input :bookable_to, :hint => "End of booking range", :as => :string, :input_html => { :type => "date" }
      = f.inputs :name => "Pricing Details", :class => "price_matrix" do
        = f.input :price, :hint => "Price per adult per day, used only for display purposes"
        -# = f.semantic_fields_for :exura_price_options do |pof|
        -#   - Date::DAYNAMES.each do |dow|
        -#     = pof.input :"price_on_#{dow.downcase}", :as => :number
      - if Spree::Config[:track_inventory_levels]
        = f.inputs :name => "Day Wise Stock", :class => "price_matrix" do
          .small Number of units per day
          - Date::DAYNAMES.each do |day|
            = f.input "on_hand_on_#{day.downcase}".to_sym, :label => "on #{day}"

     



      -# = f.inputs do
      -#   = f.input :price, :as=> :hidden, :input_html => {:value => "#{@product.price ? @product.price : '' }"}
      -#   = f.input :cost_price, :as=> :hidden, :input_html => {:value => "#{@product.cost_price ? @product.price : '' }"}


      -# = f.field_container :available_on do
      -#   = f.label :available_on, t(:available_on)
      -#   %br/
      -#   = f.error_message_on :available_on
      -#   = f.text_field :available_on, :class => 'datepicker'


      -# - unless @product.has_variants?
      -#   = f.field_container :sku do
      -#     = f.label :sku, t(:sku)
      -#     %br/
      -#     = f.text_field :sku, :size => 16

      = f.inputs :name => "for SEO purposes" do
        = f.input :permalink, :hint => "please change it only once"
        = f.input :meta_description, :as => :text
        = f.input :meta_keywords


        -# - if Spree::Config[:track_inventory_levels]
        -#   = f.field_container :on_hand do
        -#     = f.label :on_hand, t(:on_hand)
        -#     %br/
        -#     = f.number_field :on_hand, :min => 0
      -#   %ul#shipping_specs
      -#     %li#shipping_specs_weight_field
      -#       = f.label :weight, t(:weight)
      -#       = f.text_field :weight, :size => 4
      -#     %li#shipping_specs_height_field
      -#       = f.label :height, t(:height)
      -#       = f.text_field :height, :size => 4
      -#     %li#shipping_specs_width_field
      -#       = f.label :width, t(:width)
      -#       = f.text_field :width, :size => 4
      -#     %li#shipping_specs_depth_field
      -#       = f.label :depth, t(:depth)
      -#       = f.text_field :depth, :size => 4
      -# = f.field_container :shipping_categories do
      -#   = f.label :shipping_category_id, t(:shipping_categories)
      -#   %br/
      -#   = f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, { :include_blank => true }, { 'style' => 'width:200px' })
      -#   = f.error_message_on :shipping_category
      -# = f.field_container :tax_category do
      -#   = f.label :tax_category_id, t(:tax_category)
      -#   %br/
      -#   = f.collection_select(:tax_category_id, @tax_categories, :id, :name, { :include_blank => true }, { 'style' => 'width:200px' })
      -#   = f.error_message_on :tax_category
  -# %div{"data-hook" => "admin_product_form_additional_fields"}
  -#   - Spree::Variant.additional_fields.select { |af| af[:only].nil? || af[:only].include?(:product) }.each do |field|
  -#     = render :partial => 'spree/admin/shared/additional_field', :locals => { :field => field, :f => f }

app/views/spree/admin/products/edit.html.haml
= render :partial => 'spree/admin/shared/product_sub_menu'
= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Product Details' }
= render :partial => 'spree/shared/error_messages', :locals => { :target => @product }
= semantic_form_for [:admin, @product], :method => :put, :html => { :multipart => true } do |f|
  - unless @product.is_fixed_group_size_activity?
    = render :partial => 'form', :locals => { :f => f }
    = render :partial => 'spree/admin/shared/edit_resource_links'
  - else
    = render :partial => 'fixed_size_form', :locals => { :f => f }
    = render :partial => 'spree/admin/shared/edit_resource_links'

app/views/spree/admin/products/index.html.haml
= render :partial => 'spree/admin/shared/product_sub_menu'
.toolbar{"data-hook" => "toolbar"}
  %ul.actions
    %li#new_product_link
      = button_link_to "Create New Activity", new_object_url, {:remote => false, :icon => 'add', :id => 'admin_new_product'}
  %br.clear/
%h1 Listing All Activities

%table#listing_products.index
  %tr{"data-hook" => "admin_products_index_headers"}
    %th= t(:sku)
    %th= sort_link @search,:featured, "Featured", {}, {:title => "Featured on the home page" }
    %th= sort_link @search,:is_active, "Active", {}, {:title => "Active currently" }
    %th= sort_link @search,:created_at, "Created", {}, {:title => "Sort by creation date" }
    %th= sort_link @search,:updated_at, "Last Updated", {}, {:title => "Sort by last updation date" }
    %th= "Activity Type"
    %th= sort_link @search,:city, t(:city), {}, {:title => "Sort by city"}
    %th= sort_link @search,:state, t(:state), {}, {:title => "Sort by state" }
    %th{:style=>"width: 25%" }= sort_link @search,:name, t(:name), { :default_order => "desc" }, {:title => 'admin_products_listing_name_title'}
    %th Price

    %th{:style=>"width: 170px", "data-hook" => "admin_products_index_header_actions"}
  - @collection.each do |product|
    <tr #{"style='color: red;'" if product.deleted?} id="#{spree_dom_id product}" data-hook="admin_products_index_rows">
    %td= product.sku rescue '-'
    %td= product.featured
    %td= product.is_active?
    %td= (time_ago_in_words product.created_at) + ' ago'
    %td= (time_ago_in_words  product.updated_at) + ' ago'
    %td= product.activity_type.name rescue ''
    %td= product.state
    %td= product.city 
    %td= link_to product.try(:name), edit_admin_activity_path(product), :class=>"name_link", :title=>"Edit this activity"
    %td= printable_prices(product)
    %td.actions{"data-hook" => "admin_products_index_row_actions"}
      = link_to_edit product, :class => 'edit' unless product.deleted?
      \
      \#{link_to_clone product, :class => 'clone'}
      \
      \#{link_to_delete product unless product.deleted?}
= paginate @products
- content_for :sidebar do
  %div{"data-hook" => "admin_products_sidebar"}
    = search_form_for [:admin, @search] do |f|
      .box
        %h3= t(:search)
        - locals = {:f => f}
        %div{"data-hook" => "admin_products_index_search"}
          %p
            = f.label :name_cont, t(:name)
            = f.text_field :name_cont, :size => 15
          %p
            = f.label :city_cont, t(:city)
            = f.text_field :city_cont, :size => 35
          %p
            = f.label :state_cont, t(:state)
            = f.text_field :state_cont, :size => 35
          %p
            = f.label :variants_including_master_sku_cont, t(:sku)
            = f.text_field :variants_including_master_sku_cont, :size => 15
          %p
            = f.label :deleted_at_null, t(:show_deleted)
            = f.check_box :deleted_at_null, {:checked => params[:q][:deleted_at_null].blank?}, '', '1'
        %div{"data-hook" => "admin_products_index_search_buttons"}
          %p.form-buttons
            = button t(:search)

app/views/spree/admin/products/new.html.haml
= render :partial => 'spree/admin/shared/product_sub_menu'
= render :partial => 'spree/shared/error_messages', :locals => { :target => @product }
= semantic_form_for [:admin, @product], :html => { :multipart => true } do |f|
  .left{"data-hook" => "admin_product_form_left"}
    = f.inputs :name => "Basic Info" do
      = f.input :name
      = f.input :product_type, :as => :select, :collection => Spree::Product::PRODUCT_TYPES
      
      = f.input :price, :as => :hidden, :input_html => { :value => 0 }
      -# = f.input :prototype_id, :as=>:select, :collection=> Spree::Prototype.all, :hint=>"Select a prototype if you want to base this on one."
  .right
    = f.inputs :name => "Some more info" do
      = f.input :street_address
      = f.input :city
      = f.input :state, :hint => "filling these now will help search and edit this later.", :as=>:select, :collection => Spree::Product::LIST_OF_STATES
      
      #product-from-prototype.clearfix{"data-hook" => "product-from-prototype"}
        = render :file => 'spree/admin/prototypes/show' if @prototype
        = render :partial => 'spree/admin/shared/new_resource_links'

  -# .right
  -#   %h3 word of advice
  -#   %br
  -#   %p An activity should contain only static desctiption and other information that remain unchanged across variants.
  -#   %p To add pricing and inventory information, please create a variant (select from 'for child', 'for adult', 'for both') and provide the appropriate data there. The master price field is to be left blank for all practical purposes.



  -# %fieldset{"data-hook" => "new_product"}
  -#   = f.field_container :name do
  -#     = f.label :name, t(:name)
  -#     %span.required *
  -#     %br/
  -#     = f.text_field :name, :class => 'fullwidth title'
  -#     = f.error_message_on :name
  -#   .clearfix{"data-hook" => "new_product_attrs"}
  -#     .left
  -#       - unless @product.has_variants?
  -#         = f.field_container :sku do
  -#           = f.label :sku, t(:sku)
  -#           %br/
  -#           = f.text_field :sku, :size => 16
  -#           = f.error_message_on :sku
  -#       = f.field_container :prototype do
  -#         = f.label :prototype_id, t(:prototype)
  -#         %br/
  -#         = f.collection_select :prototype_id, Spree::Prototype.all, :id, :name, :include_blank => true
  -#     .right
  -#       = f.field_container :price do
  -#         = f.label :price, t(:master_price)
  -#         %span.required *
  -#         %br/
  -#         = f.text_field :price
  -#         = f.error_message_on :price
  -#       %p
  -#         = f.label :available_on, t(:available_on)
  -#         %br/
  -#         = f.error_message_on :available_on
  -#         = f.text_field :available_on, :class => 'datepicker', :style => "width:150px"
  -#   #product-from-prototype.clearfix{"data-hook" => "product-from-prototype"}
  -#     = render :file => 'spree/admin/prototypes/show' if @prototype
  -#   = render :partial => 'spree/admin/shared/new_resource_links'
:javascript
  //
    (function($){
      var base_url = "#{admin_prototypes_url}";
      var prototype_select = $('#product_prototype_id');    
      prototype_select.change(function() {
        var id = prototype_select.val();
        if (id.length) {
          $('#product-from-prototype').load([ base_url, id ].join("/"));
        } else {
          $('#product-from-prototype').empty();
        }
      })
      if (prototype_select.html() == "") {
        prototype_select.change();
      }
    })(jQuery);
  //