config/routes.rb
Mystore::Application.routes.draw do

  Spree::Core::Engine.routes.prepend do
    resources :activities, :controller => "products"
    root :to => 'home#home_page'
    ["Home", "Activities", "Contact", "About Us", "Faqs", "Partners And Operators", "Privacy Policy", "Terms And Conditions"].each do |item|
      match '/pages/:page_name' => 'home#show_pages'
    end
    namespace :admin do
      resources :activities, :controller => "products"
    end
  end

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.append do
    devise_for :users,
               :class_name => Spree::User,
               :skip => [:unlocks],
               :controllers => { :sessions => 'spree/user_sessions', 
               :omniauth_callbacks => "spree/omniauth_callbacks",
               :registrations => 'spree/user_registrations' }
    resources  :user_authentications
    match 'account' => 'users#show', :as => 'user_root'
    namespace :admin do
      resources :authentication_methods
    end
  end

  

end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/core/contact_topic.rb
module Spree
  class ContactTopic < ActiveRecord::Base
    attr_accessible :name, :email, :order_number, :message
    validates :name, :emails, :presence => true
    validates :name,          :uniqueness => true
  end
end

app/models/spree/core/contact_topic_decorator.rb
module Spree
  class ContactTopic < ActiveRecord::Base
    attr_accessible :name, :email, :order_number, :message
    validates :name, :emails, :presence => true
    validates :name,          :uniqueness => true
  end
end

app/models/spree/core/image_decorator.rb
Spree::Image.class_eval do
  attachment_definitions[:attachment][:styles] = {
    :mini => '48x48#', # thumbs under image
    :small => '100x100#', # images on category view
    :product => '400x250#', # full product image
    :large => '600x600#'  # light box image
  }
end

app/models/spree/core/order_decorator.rb
Spree::Order.class_eval do
  
  attr_accessible :booking_date

  checkout_flow do
    go_to_state :address, :if => lambda { |order| order.payment_required? }
    go_to_state :payment, :if => lambda { |order| order.payment_required? }
    go_to_state :confirm, :if => lambda { |order| order.confirmation_required? }
    go_to_state :complete
  end

  state_machine do
    after_transition :from => :cart, :to => :address do |order|
      order.next
    end
  end
  
end

app/models/spree/core/product_decorator.rb
## Add instance methods
Spree::Product.class_eval do
  
  # has_many :exura_price_options


  # Constants
  LEVELS = ['Easy', 'Moderate', 'Difficult', 'Strenuous', 'Exploratory']
  TAB_FIELDS = ['overview', 'highlights', 'features', 'reviews', 'itinerary']
  LIST_OF_STATES = ['Andaman and Nicobar', 'Daman and Diu', 'Delhi - NCT', 'Tamil Nadu', 
                    'Karnataka', 'Maharashtra', 'Jammu and Kashmir', 'Himanchal Pradesh',
                    'Orissa', 'West Bengal', 'Maharashtra', 'Kerala', 'Mizoram', 'Tripura',
                    'Nagaland', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
                    'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Goa',
                    'Gujarat', 'Meghalaya', 'Pondicherry', 'Punjab', 'Sikkim',
                    'Uttarakhand', 'Uttar Pradesh', 'Rajasthan', 'Madhya Pradesh'
                   ].uniq.sort
  PRODUCT_TYPES  = [ "Regular Activity", "Fixed Group Size Activity"]

  # Accessible attrs
  tmp = [:level, :category, :level, :category, :facilities, :items_to_bring,
         :min_passengers_reqd, :max_passengers_reqd, :overview, :highlights, :features, :reviews, :itinerary, :cancellation_policy,
         :latitude, :longitude, :zoom_level, :street_address, :city, :state, :duration, :on_hand_on_sunday, :on_hand_on_monday, :on_hand_on_tuesday,
         :on_hand_on_wednesday, :on_hand_on_thursday, :on_hand_on_friday,:on_hand_on_saturday, :product_type, :price_per_day,
         :featured, :activity_type, :bookable_from, :bookable_to
        ].each do |attr|
    attr_accessible attr
  end

  before_update :create_or_update_variants
  before_create :add_requisite_option_types
  before_save   :validate_bookable_dates

  def add_requisite_option_types
    # o = Spree::OptionType.find_by_name("Child / Adult / Both")
    # option_types << o unless option_types.include?(o)
    o = Spree::OptionType.find_by_name("Bookable on")
    option_types << o unless option_types.include?(o)
  end

  def create_or_update_variants 
    # ot = Spree::OptionType.find_by_name("Bookable on")
    # debugger
    # if booking_range_is_valid?
    #   (bookable_from..bookable_to).each do |bookable_on|
    #     v = Spree::Variant.new
    #     v.bookable_on = bookable_on
    #     ov = ot.option_values.detect { |d| Date.parse(d.presentation) == bookable_on }
    #     v.option_values << ov
    #     v.name = name
    #     v.product = self
    #     # v.price   = self.send :"price_on_#{v.bookable_on_dow}"
    #     v.on_hand = self.send :"on_hand_on_#{v.bookable_on_dow}"
    #     v.save
    #   end
    # end
  end
  
  def booking_range_is_valid?
    ! (bookable_from.blank? || bookable_to.blank? || bookable_from > bookable_to)
  end

  def validate_bookable_dates
    unless bookable_from.blank?
      if bookable_to.blank? || bookable_to < bookable_from
        errors.add :bookable_to
      end
    end
  end


  def is_active?
    !deleted_at && available_on &&
      (available_on <= Time.zone.now)
        # && (Spree::Config[:allow_backorders] || count_on_hand > 0)
  end


















  # Validations
  # validates_numericality_of :zoom_level, :unless => :new_record?
  # validates_presence_of :latitude, :longitude, :unless => :new_record?
  validates_presence_of :street_address, :city, :state
  validates :product_type, :inclusion => { :in => PRODUCT_TYPES }
  validates :level, :inclusion => { :in => LEVELS }, :unless => :new_record?

  # Validations specific to fixed group sized activity
  # validates :min_passengers_reqd, :max_passengers_reqd, :presence => true, :numericality => true, :if => :is_fixed_group_size_activity?

  # adds #is_regular_activity? and #is_fixed_group_size_activity?
  PRODUCT_TYPES.each do |t|
    define_method "is_#{t.downcase.gsub(' ', '_')}?" do
      if self.product_type
        return self.product_type == t
      else
        return false
      end
    end
  end


  # Check availability on a Day of the Week (dow param as 'mon', 'tue' etc)
  def available_on_dow?(dow)
    dow = dow.downcase
    if count_on_dow(dow) && count_on_dow(dow) > 0
      true
    else
      false
    end
  end
  def count_on_dow(dow)
    dow = dow.downcase
    self.send "on_hand_on_#{dow}".to_sym
  end

  # This is for google maps
  acts_as_gmappable :process_geocoding => false
  def gmaps4rails_address
    self.location
  end
  
  def box_image
    self.images[0] || false
  end

  def activity_type
    self.taxons.where(:parent_id => Spree::Taxon.find_by_name('Activities').id).first
  end

  def activity_type_name
    unless activity_type.nil?
      activity_type.name 
    else 
      "N/A"
    end
  end


  def location
    "#{self.city}, #{self.state}"
  end


  # Override the available? method to check for availability on a given date
  def available?
    true
  end

  # Child and Adult 
  ['child', 'adult', 'both'].each do |meth|
    define_method "variant_for_#{meth.pluralize}" do
      res = nil
      self.variants.each do |var|
        var.option_values.each do |opt|
          if opt.name == "Variant for #{meth.pluralize}"
            res = var
          end
        end
      end
      return res
    end
    define_method "price_per_#{meth}" do
      var = self.send "variant_for_#{meth.pluralize}"
      return var.price if var
    end
  end
  
  def price_today
    dow = Date::DAYNAMES[Time.now.wday]
    p = self.send :"price_on_#{dow.downcase}"
      if p.blank? 
        return p 
      else
        return spree_price
      end
  end

  
  # Override Spree's default price method to match price today and price on booking day



  def lowest_price_variant
    variants.order(:price, 'ASC').first
  end

  def prices_starting_from
    lowest_price_variant.price
  end



  def reindex
    index!
  end


end


## Add class methods
Spree::Product.instance_eval do


  def activities_list
    Spree::Taxon.where(:parent_id => Spree::Taxon.find_by_name('Activities').id)
  end

  def activities_names_list
    arr = []
    activities_list.each do |act|
      arr << act.name
    end
    return arr
  end

  def non_empty_activities_names_list
    arr = []
    activities_list.each do |act|
      if act.products.any?
        arr << act.name
      end
    end
    return arr
  end


  def active_cities_list
    arr = []
    Spree::Product.active.each do |p|
      arr << p.city.titleize rescue ''
    end
    arr.uniq
  end

  def all_cities_list
    arr = []
    Spree::Product.all.each do |p|
      arr << p.city.titleize rescue ''
    end
    arr.uniq
  end

  ## Scopes
  def featured
    where(:featured => true)
  end

  


end

app/models/spree/core/search_decorator.rb
# Spree::Search::SpreeSunspot::Search.class_eval do
#   def retrieve_products
#     conf = Spree::Search::SpreeSunspot.configuration
    
#     # send(name) looks in @properties
    
#     @properties[:sunspot] = Sunspot.search(Spree::Product) do
#       # This is a little tricky to understand
#       #     - we are sending the block value as a method
#       #     - Spree::Search::Base is using method_missing() to return the param values
#       conf.display_facets.each do |name|
#         with("#{name}_facet", send(name)) if send(name).present?
#         facet("#{name}_facet")
#       end
      
#       with(:price, Range.new(price.split('-').first, price.split('-').last)) if price
#       facet(:price) do
#         conf.price_ranges.each do |range|
#           row(range) do
#             with(:price, Range.new(range.split('-').first, range.split('-').last))
#           end
#         end
        
#         # TODO add greater than range
#       end
      
#       facet(:taxon_ids)
#       with(:taxon_ids, send(:taxon).id) if send(:taxon)
      
#       order_by sort.to_sym, order.to_sym
#       with(:is_active, true)
#       keywords(query)
#       paginate(:page => page, :per_page => per_page)
#     end
    
#     self.sunspot.results
#   end
# end




  

app/models/spree/core/taxon_decorator.rb
Spree::Taxon.class_eval do

  # Instance Methods

  def is_activity_type?
    self.parent_id == Spree::Taxon.find_by_name('Activities').id
  end

  def activity_count
    if is_activity_type?
      self.products.count
    end
  end

  def active_activities_count
    if is_activity_type?
      self.products.active.count
    end
  end

  def lowest_price_variant
    x = products.map{|p| p.lowest_price_variant}
    x.sort_by {|x| x.price}.first
  end

  def prices_starting_from
    products.sort_by{|x| x.price}.first.price
  end


 
end

  # Class Methods
  
Spree::Taxon.instance_eval do
  def all_activity_types
    act_id = Spree::Taxon.find_by_name('Activities').id
    where :parent_id => act_id
  end
  
end

app/models/spree/core/variant_decorator.rb
Spree::Variant.class_eval do
  

  after_update :reindex_everything

  # Accessible attrs

  [:bookable_from, :bookable_to, :activity_type_name, :duration, :level, :city].each do |meth|
    define_method meth do
      self.product ? (self.product.send meth) : nil
    end
  end

  def bookable_on_dow
    bookable_on.strftime('%A').downcase
  end

  def exura_available?
    if !deleted_at && !is_master? && on_hand > 0
      return true
    else
      return false
    end
  end

  def available_on
    product.available_on
  end

  def is_product_active?
    product ? product.is_active? : false
  end

  searchable do
    text :name
    string :activity_type_name, :using => :activity_type_name
    string :level, :using => :level
    string :city, :using => :city
    integer :price 
    boolean :is_product_active, :using => :is_product_active?
    time   :available_on, :trie => true
    time   :bookable_from, :trie => true
    time   :bookable_to, :trie => true
    # boolean :exura_available, :using => :exura_available?
  end


  
  def reindex_everything
    index
  end
  
end

app/models/spree/social/authentication_method.rb
class Spree::AuthenticationMethod < ActiveRecord::Base
  attr_accessible :provider, :api_key, :api_secret, :environment, :active

  def self.active_authentication_methods?
    found = false
    where(:environment => ::Rails.env).each do |method|
      if method.active
        found = true
      end
    end
    return found
  end

  scope :available_for, lambda { |user|
    sc = where(:environment => ::Rails.env)
    sc = sc.where(["provider NOT IN (?)", user.user_authentications.map(&:provider)]) if user and !user.user_authentications.empty?
    sc
  }
end

app/models/spree/social/user_authentication.rb
class Spree::UserAuthentication < ActiveRecord::Base
  attr_accessible :provider, :uid
  belongs_to :user
end

app/models/spree/social/user_decorator.rb
Spree::User.class_eval do
  has_many :user_authentications, :dependent => :destroy

  devise :omniauthable

  def apply_omniauth(omniauth)
    if omniauth['provider'] == "facebook"
      self.email = omniauth['info']['email'] if email.blank?
    end
    user_authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  def password_required?
    (user_authentications.empty? || !password.blank?) && super
  end
end

app/controllers/spree/home_controller_decorator.rb
Spree::HomeController.class_eval do
  helper 'spree/products'
  respond_to :html
  
  def home_page
    @searcher = Spree::Config.searcher_class.new(params)
    @products = @searcher.retrieve_products
    @featured = Spree::Product.featured
    respond_with(@products, @featured)
  end

  ["Home", "Activities", "Contact", "About Us", "Faqs", "Partners And Operators", "Privacy Policy", "Terms And Conditions"].each do |item|
    url = item.gsub(' ', '').underscore
    define_method url do
      render 'pages/#{url}'
    end
  end
  def show_pages
    @page_name = params[:page_name]
    render :page_name
  end

end

app/controllers/spree/orders_controller_decorator.rb
Spree::OrdersController.class_eval do
 def populate
   @order = current_order(true)
   
   params[:products].each do |product_id,variant_id|
     quantity = params[:quantity].to_i if !params[:quantity].is_a?(Hash)
     quantity = params[:quantity][variant_id].to_i if params[:quantity].is_a?(Hash)
     @order.add_variant(Variant.find(variant_id), quantity) if quantity > 0
   end if params[:products]
   
   params[:variants].each do |var|
     variant_id = var[:id]
     quantity   = var[:quantity]
     quantity = quantity.to_i
     @order.add_variant(Spree::Variant.find(variant_id), quantity) if quantity > 0
   end if params[:variants]
   
   fire_event('spree.cart.add')
   fire_event('spree.order.contents_changed')
   respond_with(@order) { |format| format.html { redirect_to cart_path } }
 end
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do
  def index
    @current = 'products'
    @search = Sunspot.search(Spree::Variant) do
      # facet :bookable_on
      # facet :price
      facet :activity_type_name
      facet :city
      facet :level
      fulltext params[:keyword]
      with :is_product_active, true
      if params[:as].present? && !params[:ae].present?
        with(:bookable_from).less_than(Date.parse(params[:as]).to_time)
        with(:bookable_to).greater_than(Date.parse(params[:as]).to_time)
      end
      if params[:ae].present? && !params[:as].present?
        with(:bookable_from).less_than(Date.parse(params[:ae]).to_time)
        with(:bookable_to).greater_than(Date.parse(params[:ae]).to_time)
      end
      if params[:as].present? && params[:ae].present?
        with(:bookable_from).less_than(Date.parse(params[:as]).to_time)
        with(:bookable_to).greater_than(Date.parse(params[:ae]).to_time)
      end
      if params[:act].present?
        with :activity_type_name, params[:act]
      end
      if params[:lvl].present?
        with :level, params[:lvl]
      end
      if params[:loc].present?
        with :city, params[:loc]
      end
    end
    @products = @search.results
  end
  

end

app/views/spree/home/home_page.html.haml
#home_slider.blueberry
  %ul.slides.crop
    - 7.times do |i|
      %li
        = image_tag "home_slider/#{i+1}.jpg"
  .slider_texture
#BigMarketingMessage
  %h1 We bring to you, the best adventure experiences from all around Incredible !ndia
#cannonball
  %h2 Search Activities
  %h4 Plan your most thrilling vacation with us yet!
  - @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Spree::Taxon.roots
  = form_tag activities_path, :method => :get do
    -# = select_tag :taxon,                               |
    -# options_for_select([[t(:all_departments), '']] + |
    -# @taxons.map {|t| [t.name, t.id]},              |
    -# @taxon ? @taxon.id : params[:taxon])             |
    // .field
    //   %label Vacation start date
    //   %input{:type => "date", :value => "#{ params[:as].blank? ? Date.today : params[:as]}", :name=>"as"}
    // .field
    //   %label Vacation end date
    //   %input{:type => "date", :value => "#{ params[:ae].blank? ? Date.today : params[:as]}", :name=>"ae"}
    
    .field
      %label{:for=>"activity_type"} Activity Type
      = select_tag :act, options_for_select(Spree::Product.non_empty_activities_names_list.sort, params[:act]), {:prompt => 'ALL'}
    .field
      %label{:for=>"level"} Level
      = select_tag :lvl, options_for_select(Spree::Product::LEVELS.sort, params[:lvl]), {:include_blank => 'Select activity location'}
    .field
      %label{:for=>"location"} Location
      = select_tag :loc, options_for_select(Spree::Product.active_cities_list.sort, params[:loc]), {:include_blank => 'Select activity location'}
    .field.ar
      = submit_tag "Go!", :name => nil, :class=>"btn"
#carousel
  %h2 Browse Actitvities
  %a.carousel-control.left{"data-slide" => "prev", :href => "#myCarousel"} &lsaquo;
  %a.carousel-control.right{"data-slide" => "next", :href => "#myCarousel"} &rsaquo;
  .car_wrapper
    - Spree::Taxon.all_activity_types.each do |act|
      - if act.active_activities_count > 0
        %a.activity_box{:href=>products_path(:act=>act.name)}
          .img
            = image_tag act.icon.url(:original), :class=>"pictogram"
          .detail
            %h4= act.name.titleize
            .number
              = pluralize(act.active_activities_count, 'activity')
            .number
              from
              = number_to_currency act.prices_starting_from rescue ''
#main_container
  .left_col
    %div{"data-hook" => "homepage_featured_products"}
      %h3
        Featured Activities
      - @featured.each do |pr|
        - @product = pr
        %a.box{:href=>url_for(@product), :title=>"#{@product.name} | #{@product.location}"}
          - if @product.images[0]
            .img{:style=>"background-image: url('#{@product.images[0].attachment.url(:original)}')"}
            .details
              %h3
                = @product.name.truncate 30
              %p.infos
                = image_tag @product.activity_type.icon, :class=>"pictogram" rescue ''
                %span= @product.activity_type.name.titleize rescue ''
                \/
                %span.price= number_to_currency @product.price rescue ''
                \/
                = @product.location
                \/
                = @product.level
              %p
                = @product.description.truncate(120) rescue ''

  -# - unless @featured.nil?
  -#   .left_col
  -#     %div{"data-hook" => "homepage_featured_products"}
  -#       %h3 Featured Activities
  -#       = render :partial => 'spree/products/product_box', :locals => {:products => @featured}, :collection => @feaured
  -#   .right_col
  .right_col
    %div{"data-hook" => "homepage_featured_products"}
      %br
      %br
      %br
      %br
      - @featured.each do |pr|
        - @product = pr
        %a.box{:href=>url_for(@product), :title=>"#{@product.name} | #{@product.location}"}
          - if @product.images[0]
            .img{:style=>"background-image: url('#{@product.images[0].attachment.url(:original)}')"}
            .details
              %h3
                = @product.name.truncate 30
              %p.infos
                = image_tag @product.activity_type.icon, :class=>"pictogram" rescue ''
                %span= @product.activity_type.name.titleize rescue ''
                \/
                %span.price= number_to_currency @product.price rescue ''
                \/
                = @product.location
                \/
                = @product.level
              %p
                = @product.description.truncate(120) rescue ''
  -#  %h5 Videos
  -#  %iframe{:height => 200, :width => 350, :frameborder => "0", :src => "http://www.youtube.com/embed/fKmSF0sf31g"}
  -#  %p
  -#  %iframe{:height => 200, :width => 350, :frameborder => "0", :src => "http://www.youtube.com/embed/HG5AuhrrPOc"}
    
    -# feed = Feedzirra::Feed.fetch_and_parse("http://exurajourneys.wordpress.com/category/videos/feed")
    -# = feed.to_json
    -# - feed.entries.each do |e|
    -#   .post
    -#     .post_title
    -#       = e.title
    -#     %p
    -#       = e.summary.truncate(140)
    -#       %a.fr.more{:href=> e.url, :target=>"blank"} more
    -# %h5 Adventure Zone
    -# - feed.entries[0..4].each do |e|
    -#   .post
    -#     .post_title= e.title
    -# %h5 Recent Videos
    -# - feed.entries[0..4].each do |e|
    -#   .post
    -#     .post_title= e.title
      
  - content_for :sidebar do
    -# %div{"data-hook" => "homepage_sidebar_navigation"}
      -# = render :partial => 'spree/shared/taxonomies'
    -# %div{"data-hook" => "homepage_products"}
      -# = render :partial => 'spree/shared/products', :locals => { :products => @products } unless @products
  -# %div{"data-hook" => "homepage_products"}
  -#   = render :partial => 'spree/products/product_box', :collection => @products, :as => :product unless @products

app/views/spree/home/index.html.haml
-# #home_slider.blueberry
-#   %ul.slides.crop
-#     - 10.times do |i|
-#       %li
-#         = image_tag "slider/#{i+1}.jpg"
-#   .slider_texture
-#   .fwc.abs
-#     #cannonball.twist
-#       .untwist
-#         %h4 Plan your most thrilling vacation with us yet!
-#         %form
-#           .field
-#             %label Vacation Start Date
-#             %input{:type=>"text"}
-#           .field
-#             %label Vacation End Date
-#             %input{:type=>"text"}
-#           .field
-#             %label Destination
-#             %input{:type=>"text"}
-#           .field
-#             %label Activity Type
-#             %input{:type=>"text"}
-#           .field
-#             %label Activity Level
-#             %input{:type=>"text"}
-#           .field.ar
-#             %a.btn.twist{:href=>"#"} Search &#9889;
-# #carousel.fwc
-#   - Spree::Taxon.all_activity_types.each do |act|
-#     - if act.activity_count > 0
-#       %a.activity_box{:href=>seo_url(act)}
-#         .img
-#           = image_tag act.icon.url(:original), :class=>"pictogram"
-#         .detail
-#           %h4= act.name.titleize
-#           .number
-#             = pluralize(act.activity_count, 'activity')
-#   -# - ['FourWheelDrive', 'WaterSurfing', 'WhaleViewing', 'IceFishing', 'SkiJump', 'Sailing', 'WaterMotorBoating', 'WaterCraft','Trekking', 'ScubaDiving', 'Sledding', 'MotorBikeTrail', 'CableCar'].each do |item|
-#   -#   %a.activity_box{:href=>'#'}
-#   -#     .img
-#   -#       = image_tag "pictograms/#{item}.png", :class=>"pictogram"
-#   -#     .detail
-#   -#       %h4= item.underscore.gsub('_',' ').titleize
-#   -#       .number
-#   -#         = pluralize((rand(100)+1), 'activity')
-#   -#       .price
-#   -#         starting from
-#   -#         = number_to_indian_currency((rand(10)+1)*100)
-# #main_container
-# - content_for :sidebar do
-#   %div{"data-hook" => "homepage_sidebar_navigation"}
-#     = render :partial => 'spree/shared/taxonomies'
-# %div{"data-hook" => "homepage_products"}
-#   = render :partial => 'spree/products/product_box', :collection => @products, :as => :product unless @products

app/views/spree/home/page_name.html.haml
#main_container.pages
  - case @page_name
  - when "partners_and_operators"
    = render :partial => 'spree/shared/partner'
  - when "about_us"
    = render :partial => 'spree/shared/aboutus'
  - when "privacy_policy"
    = render :partial => 'spree/shared/privacy'   
  - when "terms_and_conditions"
    = render :partial => 'spree/shared/team'
  - when "faqs"  
    = render :partial => 'spree/shared/faqs'
     
           